# Generated by Django 3.0.4 on 2020-04-01 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='選手名')),
                ('nationality', models.CharField(max_length=225, verbose_name='代表チーム')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='チーム名')),
                ('HO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='HO_player', to='rugby_team_create.Player', verbose_name='フッカー')),
                ('LO1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='LO1_player', to='rugby_team_create.Player', verbose_name='左ロック')),
                ('PR1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PR1_player', to='rugby_team_create.Player', verbose_name='左プロップ')),
                ('PR2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PR2_player', to='rugby_team_create.Player', verbose_name='右プロップ')),
            ],
        ),
    ]
