# Generated by Django 3.0.4 on 2020-04-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugby_team_create', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='creater_name',
            field=models.CharField(max_length=225, null=True, verbose_name='製作者名'),
        ),
    ]
