# Generated by Django 3.0.4 on 2020-04-11 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rugby_team_create', '0003_auto_20200411_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='creater_name',
            new_name='creator_name',
        ),
    ]
